before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
    - 386

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

  binary: '{{ .ProjectName }}'
  main: cmd/BeeScan-scan.go

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256
